server:
  port: 10000

spring:
  application:
    name: zuul-demo

zuul:
  prefix: /zuul
  routes:
     myserver:
         service-id: server-demo
         path: /yang/**
  ignored-services: "*"

eureka:
  client:
    service-url:
      defaultZone : http://localhost:9099/eureka


